### ISSUE TITLE
How to transform visualized flow png into flow arrays?

### ISSUE THREAD

**Issue by G1tQuality** [DQiaole/MemFlow#6]
Is this a reverse process for flow_viz.py?
(我想根据前向光流和反向光流用[checking for consistent forward and backward flow](https://blog.csdn.net/TSthinker/article/details/127296263)的方法来计算Occlusion mask，但是直接输出光流tensor的json文件有100多MB，速度比较慢。以上的逆过程会更快占用空间更小吗？同时请问大佬有什么效果较好的方法得到Occlusion mask吗？）

**Comment by DQiaole** [comment]
Instead of using `flow_viz.flow_to_image` (which is designed for visualization), please use the function `writeFlow`, `writeFlo5File` or `writeFlowKITTI` within https://github.com/DQiaole/MemFlow/blob/main/core/utils/frame_utils.py for flow saving. 

As for occlusion mask, you can use the methods provided in your link.
